### ISSUE TITLE
[FEATURE] Dark Theme

### ISSUE THREAD

**Issue by publikphigor** [csdojo-defaang/defaang#183]
### Description

``` js
It'll definitely be nice to have a dark theme and a toggle in the navbar.
Since we're using Tailwind CSS, it'll make sense to add dark theme now before the codebase gets larger.

**Comment by yung-coder** [comment]
Yeah i would like to work on it ..

**Comment by Preet-Sojitra** [comment]
> ### Description
> 
> ```js
> It'll definitely be nice to have a dark theme and a toggle in the navbar.
> Since we're using Tailwind CSS, it'll make sense to add dark theme now before the codebase gets larger.
> ```

There is already an opened issue (Issue #82 ) for color theme.

**Comment by Princeton21** [comment]
@ykdojo Kindly close this issue.👍
