### ISSUE TITLE
Style: Padding of 'How it work' section for RWD

### ISSUE THREAD

**Issue by TreciaKS** [csdojo-defaang/defaang#210]
### Description

I noticed that the padding of the 'How it works' section creates a lot of whitespace.

I would like to work on the responsiveness on this section so that the site displays well on smaller screens.

### Screenshots

<img width="377" alt="how-it-works-section" src="https://user-images.githubusercontent.com/82657928/192502874-69f69a50-a11d-4214-a59f-7438dc5878d5.png">

**Comment by ykdojo** [comment]
Sounds good! Thank you @TreciaKS

**Comment by Princeton21** [comment]
@TreciaKS What's the update on your issue?

**Comment by TreciaKS** [comment]
Excuse me for delaying, I've been so preoccupied with work
responsibilities.

I'll be sure to work on and close this issue as soon as possible. By
Saturday

**Comment by TreciaKS** [comment]
<img width="1222" alt="Screenshot 2022-10-29 at 10 59 21" src="https://user-images.githubusercontent.com/82657928/198823079-48f853ba-2a4c-4491-b32c-804b20ce4cb1.png">

I am currently facing an issue. I followed the starting my project guide `npm install > npm run dev` strictly and this is what I'm facing since I've ran `npm un dev`

How to solve this?
