### ISSUE TITLE
[DOCS]  SUGGESTION: Minor issues with the contribution guidelines

### ISSUE THREAD

**Issue by slim-codes** [csdojo-defaang/defaang#219]
### Description

Some of the instructions in the [CONTRIBUTING.md](https://github.com/ykdojo/defaang/edit/main/CONTRIBUTING.md) document are confusing. The confusing instructions appear under these two sections: **Making Changes** and **Pushing Changes**.

### under Making Changes section
- Use **run** instead of **call** in step 1 and 2 under **Making Changes** section, shell instructions are **commands** not **functions**. Hence are not callable.

- Step 7 is unnecessary and should be removed. Note that step 7 tells the reader to repeat steps 2 - 5. Repeating step 2 will cause git to display:
 `fatal: a branch named 'feature' already exists
`
### under Pushing Changes section

- step 1 says "Follow the instructions for Updating Your Repository". This statement is rather confusing because it's ambiguous

- Firstly, Updating Your Repository is written with title case (each word is capitalized). This gives the wrong impression that there's a section titled Updating Your Repository somewhere in this document which there isn't. 
- Secondly, On reading the quoted instruction above, I assume that the author meant to say **Follow these** instead of **Follow the**. I could be wrong
- This section uses the `rebase` command instead of `merge`. IMHO `merge name-of-your-feature main` is better and much safer than using `rebase`. Plus newcomers are more familiar with the `merge` command

Link to associated file: [CONTRIBUTING.md](https://github.com/ykdojo/defaang/edit/main/CONTRIBUTING.md)

@ykdojo If you approve of my suggestions, I would like to implement these changes as part of my first time participating in hacktoberfest.

**Comment by ykdojo** [comment]
@slim-codes thank you.

Would you mind sending these changes as a PR so they're easier to review in the right context?

**Comment by slim-codes** [comment]
> @slim-codes thank you.
> 
> Would you mind sending these changes as a PR so they're easier to review in the right context?

Sure!
I just saw you typing these on discord 😂😂
