### ISSUE TITLE
[FEATURE] Highlight email input if its wrong.

### ISSUE THREAD

**Issue by sohamdata** [csdojo-defaang/defaang#252]
### Description

Highlight email input if its invalid (e.g. name@example. ). Also display a message below email input.
(very simple but I would be happy to contribute :) )

**Comment by sohamdata** [comment]
demo:
![inputEmail](https://user-images.githubusercontent.com/78294692/194084526-4e8ff410-b6a5-4f28-988e-f32c1180be04.gif)

**Comment by ykdojo** [comment]
Looks good! Thank you
