### ISSUE TITLE
[FEATURE] Add a scroll to top button

### ISSUE THREAD

**Issue by sohamdata** [csdojo-defaang/defaang#254]
### Description

 [FRONTEND] Add scroll to top button. I'd be happy to contribute.

**Comment by sohamdata** [comment]
demo:
![scrollToTop](https://user-images.githubusercontent.com/78294692/194111584-db5bc3cc-f48f-4272-b96a-2d82a8f6b041.gif)

**Comment by ykdojo** [comment]
Thank you, but I don't think it's necessary to have this feature.
