### ISSUE TITLE
[DX] Copy over the project board to this new org.

### ISSUE THREAD

**Issue by ykdojo** [csdojo-defaang/defaang#306]
### Description

I created this new org (csdojo-defaang) to house all relevant projects here.

However, it seems like [there's no easy way to copy a project board to an org](https://github.com/community/community/discussions/36598).

So, we'll probably need to manually copy everything in [this board](https://github.com/users/ykdojo/projects/1/views/1) to a new board here.

**Comment by ykdojo** [comment]
@subhoghoshX let me do that right now

**Comment by ykdojo** [comment]
Done: https://github.com/orgs/csdojo-defaang/projects/2/views/1

**Comment by epicadidash** [comment]
Would love to do that @ykdojo

**Comment by ykdojo** [comment]
@epicadidash thanks! I tried to add you as a collaborator on the project, but GitHub wasn't letting me for some reason.

@subhoghoshX I made you an admin - do you want to try adding @epicadidash on your end?

**Comment by subhoghoshX** [comment]
Thanks, @ykdojo. I don't appear to have any escalated access or access to any new tab or something.

**Comment by ykdojo** [comment]
I meant the project. There's no place to add a new collaborator there?

**Comment by subhoghoshX** [comment]
Ah, now I see. But no worries, I just moved the projects myself.

**Comment by ykdojo** [comment]
Thank you so much @subhoghoshX!
