### ISSUE TITLE
[DOCS] Update the project board link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ykdojo** [csdojo-defaang/defaang#311]
### Description

Now that our project board has been moved from a personal account to this org account (#306), we should update the link in CONTRIBUTING.md accordingly.

**Comment by Frey0-0** [comment]
I would like to take this issue @ykdojo

**Comment by Frey0-0** [comment]
please also provide reference to the link you are talking about here

**Comment by ykdojo** [comment]
@Frey0-0 can you do your best to find it yourself?

**Comment by Frey0-0** [comment]
okay I will try @ykdojo assign me the issue

**Comment by Frey0-0** [comment]
@ykdojo It was very easy haha I have linked a PR to this issue. Please review it.

**Comment by Frey0-0** [comment]
I think I have completed this issue, it was actuallyy easy @ykdojo please review it
